### PR TITLE
Fix topic not exist when partition num is 1

### PR DESCRIPTION
**Pull request by wolfstudy**
Fixes: #249 

Fix topic not exist when partition num is 1

### CODE REVIEW

**Comment by wolfstudy** [comment]
@codelipenghui @merlimat PTAL thanks?

**Review by vongosling — APPROVED** [review]

**Review by merlimat — CHANGES_REQUESTED** [review]
I don't think this is the right change since there is a difference between partitioned and non-partitioned topics.

An alternative, when auto-topic creation is disabled, would be to force the creation of a non-partitioned topic. Eg. :


```java
adminClient.topics(). createNonPartitionedTopicAsync(topic);
```

**Comment by dave2wave** [comment]
I agree with Matteo. There are 1 topic, 1 partition workloads why break them?

**Comment by vongosling** [comment]
Good feedback.

**Pull request closed without merging**
