### PR TITLE
Updates for Kafka and Pulsar JMS Benchmarks

### PR DESCRIPTION
**Pull request by dave2wave**
Here is a summary of all that is in this PR.

#### Framework pom
- Add driver-jms
- Update netty-all dependency due to using openjdk11

#### Benchmark
- Add --extra option to allocate more consumer workers than producer workers.
  
#### WorkloadGenerator
- createProducers before createConsumers
- ensureTopicsAreReady is no longer needed for Kafka (?)

#### DistributedWorkerEnsemble
- Optionally create more consumer workers then producer workers
- If there is an odd number of workers allocate the extra as a consumer

#### LocalWorker
- Fix typo in variable name

#### create_charts.py
- Add chart types
- Update some of the labels

#### driver-jms
- Updated README.md
- Some driver yaml file tweaks
- Scripts to update the OMB gzip to include a JMS Client
- JMSBenchmarkConsumer
  - Use property for end to end latency.
  - Simply close the connection.
- JMSBenchmarkDriver
  - create JMSBenchmarkTransactionProducer when requested
- JMSBenchmarkProducer
  - Use property for end to end latency.
- JMSBenchmarkTransactionProducer
  - Added
- JMSConfig
  - sendWithTransactions property

#### driver-kafka deployments
- Upgrade version from 2.3.0 to 2.8.1
- Use ASF archive instead of mirror.
- Configure driver-jms/kafka- drivers
- Use AWS spot instances
- Use openjdk11
- Update the pom from Kafka 2.4.0 to 2.8.1 (Note pom and deploy.yaml were mismatched)

#### driver-pulsar deployments
- Upgrade version from 2.4.0 to 2.8.1
- Use downloads.apache.org as mirrors.cgi is deprecated by ASF.
- Configure pulsar transaction mode
- Configure driver-jms/pulsar- drivers
- Use AWS spot instances
- Use openjdk11
- pulsar_env.ah template - remove dropped JVM options

#### driver-pulsar
- PulsarBenchmarkDriver
  - comment out adminClient call to setBacklogQuota
- Overall pom file
  - don't force jdk 1.8 build - provide option
  - force the version of the netty-all dependency

### CODE REVIEW

**Comment by dave2wave** [comment]
On the first conflict please take the added line which adds a property. The second conflict is whitespace,

**Comment by dave2wave** [comment]
FYI - @merlimat @vongosling @eolivelli

**Comment by vongosling** [comment]
@dave2wave Did you run it on your platform? Some conflicts could be resolved:-）

**Comment by Moengger** [comment]
Whether Added --extra option help to improve performance？Have any test data？

**Comment by dave2wave** [comment]
> @dave2wave Did you run it on your platform? Some conflicts could be resolved:-）

Yes, these changes have been run and tested on AWS instances.

There is one file with two conflicts that can be easily resolved - see my prior comment.

**Comment by dave2wave** [comment]
> Whether Added --extra option help to improve performance？Have any test data？

It does for our Pulsar JMS testing. It is an option so as not to impact everyone else's testing.

**Comment by dave2wave** [comment]
I've rebased these changes and will be submitting new PRs

**Pull request closed without merging**
